### ISSUE TITLE
Uninstall Remnants

### ISSUE THREAD

**Issue by martynjy** [sezanzeb/alsa-control#2]
After uninstalling 'alsa-control' it has left the following remnants in mixer:

alsacontrol-input-mute
alsacontrol-input-volume
alsacontrol-output-mute
alsacontrol-output-volume

**Comment by sezanzeb** [comment]
probably from the ~/.asoundrc file. I think there is an include statement that should be deleted or something.

alsa-control is just a configurator for that config file, there isn't really much more going on

**Comment by martynjy** [comment]
No not ~/.asoundrc.  I deleted asound.state also.  The entries appear in alsamixer and I tried kmix and they also show.  Looked in dmix.conf and nothing there.

**Comment by sezanzeb** [comment]
So .asoundrc is empty?

I think for changes to take effect I had to play some sound. Did you try playing some, and do the mixers disappear afterwards?

Also, applications need to restart afterwards. Did you try rebooting?

**Comment by martynjy** [comment]
Rebooted every time I've tried something.  They keep reappearing in 'asound.state'.

**Comment by sezanzeb** [comment]
As a last resort to find where that stuff is (even though alsa-control only writes an include statement to ~/.asoundrc) you can try to search for the string

```bash
sudo ack alsacontrol-input-mute /root /etc /var /home
```

this may take some time to complete

**Comment by martynjy** [comment]
Only 'asound.state' found by ack.

**Comment by sezanzeb** [comment]
incredible. no idea where it would come from

**Comment by sezanzeb** [comment]
I'm using pipewire nowadays

**Comment by martynjy** [comment]
Yes I know it is VERY odd.  I can usually track these things down.  I'll keep scratching my head but right now I haven't got a clue!

**Comment by martynjy** [comment]
Solved.  There is a alsactl command 'clean' which clears / resets the controls.  So 'alsactl clean' cleared the remnants.
